In [48]:
# Part II no. 1
from sklearn.feature_extraction.text import TfidfVectorizer
import glob
import os
import numpy as np

# get all txt filenames in a folder
doc_files = glob.glob(r'D:\Programming Exercise 2\resources\documents\*.txt')
#print(doc_files[:7])
        
def sort_key(s):
    size=len(s)
    size=-size
    num=0
    #print(s)
    for i in range(-5, size,-1):
        try:
            num=int(s[i])
            #print(num)
        except:
            #print(s[i+1:-4])
            return int(os.path.basename(s)[i+1:-4])

doc_files.sort(key=sort_key)

In [49]:
# method to read all lines in a document and return it as a string
def read_all_lines(file):
    with open(file, 'r') as f:
        lines = f.read().replace('\n', '')
        #lines = f.read()
    return lines

# build doc corpus
doc_corpus = []
for fileName in doc_files:
    text = read_all_lines(fileName)
    doc_corpus.append(text)

print(len(doc_corpus))
# create vector space representations using standard TF-IDF weighting scheme
vectorizer = TfidfVectorizer()

X_doc = vectorizer.fit_transform(doc_corpus)
# print(vectorizer.get_feature_names())
print(X_doc.shape)
#print(X)

2500
(2500, 5032)


In [50]:
# Part II no. 2
# get all txt filenames in a folder
query_files = sorted(glob.glob(r'D:\Programming Exercise 2\resources\queries\*.txt'))

query_files.sort(key=sort_key)

# build query corpus
from nltk.corpus import stopwords
stoplist = stopwords.words('english')
query_corpus = []

for fileName in query_files:
    text = read_all_lines(fileName)
    clean_word_list = [word for word in text.split() if word not in stoplist] 
    text = " " 
    text = text.join(clean_word_list)
    query_corpus.append(text)

X_query = vectorizer.transform(query_corpus)
# print(vectorizer.get_feature_names())
print(X_query.shape)
# print(X_query)

(3, 5032)


In [51]:
from sklearn.metrics.pairwise import cosine_similarity
query_num,doc_num=X_query.shape[0],X_doc.shape[0]
cos_dis=np.zeros((query_num,doc_num))

for i in range(query_num):
    for j in range(doc_num):
        cos_dis[i][j]=cosine_similarity(X_query[i],X_doc[j])

In [52]:
res=np.zeros((query_num, 10))

for i in range(query_num):
    candidates=cos_dis[i]
    cur_res=candidates.argsort()[::-1][:10]
    res[i]=cur_res

In [53]:
print(res)

[[1137. 1497. 2324. 2387.  354.  362.  334.  342.  718. 1473.]
 [1226.  795. 1682. 1687. 1042. 1197. 1196.  542. 1689. 1680.]
 [ 986. 2195.  351.  350.  324.  983.  326.  331.  156.  128.]]
